name: CI/DI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
      uses: actions/setup-node@v3
        with:
          node-version: '22.13.0'
      
      - name: Install dependencies
        run: |
          npm install
        
      - name: Run tests
        run: |
          npm test --watchAll=false

      - name: Build     
      - name: npm run build
        run: |
          npm run build   
      - name: Upload artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build

          deploy:
          needs: build
          runs-on: ubuntu-latest
          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./build

          - name: Deply to Github Pages
      uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.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 }}
            publish_dir: ./build
        
          
